# Generated by Django 3.0.5 on 2020-04-29 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_artevents_artist_concert_exhibition_held_location_perform_theater_tickethas_time_ton'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='held',
            name='eid',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='perform',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='eid',
        ),
        migrations.DeleteModel(
            name='TicketHas',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.RemoveField(
            model_name='ton',
            name='eid',
        ),
        migrations.DeleteModel(
            name='ArtEvents',
        ),
        migrations.DeleteModel(
            name='Concert',
        ),
        migrations.DeleteModel(
            name='Exhibition',
        ),
        migrations.DeleteModel(
            name='Held',
        ),
        migrations.DeleteModel(
            name='Perform',
        ),
        migrations.DeleteModel(
            name='Theater',
        ),
        migrations.DeleteModel(
            name='TOn',
        ),
    ]
