# Generated by Django 2.1.5 on 2020-04-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_time_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('Lid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('longitude', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='art_events',
            name='id',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='id',
        ),
        migrations.RemoveField(
            model_name='music',
            name='id',
        ),
        migrations.RemoveField(
            model_name='t_on',
            name='id',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ticket_has',
            name='id',
        ),
        migrations.RemoveField(
            model_name='time',
            name='Tday',
        ),
        migrations.RemoveField(
            model_name='time',
            name='Tmonth',
        ),
        migrations.RemoveField(
            model_name='time',
            name='Tyear',
        ),
        migrations.RemoveField(
            model_name='time',
            name='id',
        ),
        migrations.AlterField(
            model_name='art_events',
            name='Eid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Aid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='Eid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='Eid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='t_on',
            name='Eid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='theater',
            name='Eid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket_has',
            name='Eid',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket_has',
            name='Tid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='time',
            name='time_serial',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
