# Generated by Django 2.1.5 on 2020-04-21 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200415_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtEvents',
            fields=[
                ('eid', models.CharField(db_column='Eid', max_length=60, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('e_image', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Art_Events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketHas',
            fields=[
                ('tid', models.CharField(db_column='Tid', max_length=20, primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('refund_policy', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Ticket_has',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Art_Events',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='T_on',
        ),
        migrations.DeleteModel(
            name='Ticket_has',
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='exhibition',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='held',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='perform',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='theater',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('eid', models.ForeignKey(db_column='Eid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.ArtEvents')),
                ('concert_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Concert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TOn',
            fields=[
                ('eid', models.ForeignKey(db_column='Eid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.ArtEvents')),
            ],
            options={
                'db_table': 'T_on',
                'managed': False,
            },
        ),
    ]
