# Generated by Django 2.1.5 on 2020-04-21 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200421_0331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'managed': True},
        ),
    ]
