# Generated by Django 3.0.4 on 2020-04-23 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200421_0409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artevents',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'managed': False},
        ),
    ]
