# Generated by Django 3.0.5 on 2020-04-29 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0002_auto_20200423_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtEvents',
            fields=[
                ('eid', models.CharField(db_column='Eid', max_length=60, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('e_image', models.CharField(blank=True, max_length=200, null=True)),
                ('seatmap', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Art_Events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('aid', models.CharField(db_column='Aid', max_length=20, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(blank=True, max_length=40, null=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Artist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('lid', models.CharField(db_column='Lid', max_length=20, primary_key=True, serialize=False)),
                ('longitude', models.CharField(blank=True, max_length=30, null=True)),
                ('latitude', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketHas',
            fields=[
                ('tid', models.CharField(db_column='Tid', max_length=20, primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('refund_policy', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Ticket_has',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('time_serial', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_ymd', models.CharField(blank=True, db_column='date_YMD', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('eid', models.OneToOneField(db_column='Eid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='music.ArtEvents')),
                ('concert_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Concert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('eid', models.OneToOneField(db_column='Eid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='music.ArtEvents')),
                ('background', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Exhibition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Held',
            fields=[
                ('eid', models.OneToOneField(db_column='Eid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='music.ArtEvents')),
            ],
            options={
                'db_table': 'held',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perform',
            fields=[
                ('eid', models.OneToOneField(db_column='Eid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='music.ArtEvents')),
            ],
            options={
                'db_table': 'Perform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('eid', models.OneToOneField(db_column='Eid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='music.ArtEvents')),
                ('genre', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Theater',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TOn',
            fields=[
                ('eid', models.OneToOneField(db_column='Eid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='music.ArtEvents')),
            ],
            options={
                'db_table': 'T_on',
                'managed': False,
            },
        ),
    ]
