# Generated by Django 2.1.5 on 2020-04-21 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200421_0328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artevents',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='artist',
            table='Artist',
        ),
        migrations.AlterModelTable(
            name='exhibition',
            table='Exhibition',
        ),
        migrations.AlterModelTable(
            name='held',
            table='held',
        ),
        migrations.AlterModelTable(
            name='location',
            table='Location',
        ),
        migrations.AlterModelTable(
            name='perform',
            table='Perform',
        ),
        migrations.AlterModelTable(
            name='theater',
            table='Theater',
        ),
        migrations.AlterModelTable(
            name='time',
            table='Time',
        ),
    ]
